package com.lucidcoders.tournamentscraper.rest;

public enum CasinoBank {
    
    AMERISTAR_BLACK_HAWK("Ameristar Black Hawk", 1),
    AMERISTAR_EAST_CHICAGO("Ameristar East Chicago", 2),
    AMERISTAR_KANSAS_CITY("Ameristar Kansas City", 3),
    AMERISTAR_ST_CHARLES("Ameristar St. Charles", 4),
    AMERISTAR_VICKSBURG("Ameristar Vicksburg", 5),
    ARIA("Aria Resort & Casino", 6),
    ATLANTIS("Atlantis Casino", 7),
    BALLYS_LAS_VEGAS("Bally's Las Vegas", 8),
    BEAU_RIVAGE("Beau Rivage", 9),
    BELLAGIO("Bellagio", 10),
    BELTERRA("Belterra Casino Resort", 11),
    BIG_EASY("The Big Easy Poker Room at Mardi Gras Casino", 12),
    BLACK_BEAR("Black Bear Casino Resort", 13),
    BOOMTOWN_NEW_ORLEANS("Boomtown Casino New Orleans", 14),
    BORGATA("Borgata Hotel Casino & Spa", 15),
    BOULDER_STATION("Boulder Station", 16),
    BUFFALO_THUNDER("Buffalo Thunder", 17),
    CACHE_CREEK("Cache Creek", 18),
    CACTUS_PETES("Cactus Petes", 19),
    CAESARS_PALACE("Caesars Palace", 20),
    CAESARS_WINDSOR("Caesars Windsor", 21),
    CAMEO_CLUB("Cameo Club Casino", 22),
    CANNERY("Cannery", 23),
    CANTERBURY_PARK("Canterbury Park Card Casino", 24),
    CAPITOL("Capitol Casino", 25),
    DEL_SOL("Casino Del Sol Resort", 26),
    MIAMI("Casino Miami", 27),
    CHEROKEE_ROLAND("Cherokee Casino Roland", 28),
    CHEROKEE_WEST_SILOAM("Cherokee Casino West Siloam", 29),
    CHOCTAW_DURANT("Choctaw Casino Durant", 30),
    CHOCTAW_GRANT("Choctaw Grant", 31),
    CHOCTAW_POCOLA("Choctaw Pocola", 32),
    CHUMASH("Chumash Casino Resort", 33),
    CLUB_52_POKER_ROOM("Club 52 Poker Room", 34),
    COMMERCE("Commerce Casino", 35),
    COUSHATTA("Coushatta Casino", 36),
    DAYTONA_BEACH_POKER_ROOM("Daytona Beach Poker Room", 37),
    DELAWARE_PARK("Delaware Park Casino", 38),
    DESERT_DIAMOND_NOGALES("Desert Diamond Nogales", 39),
    DIAMOND_JIMS("Diamond Jim's Casino", 40),
    DIAMOND_JO_WORTH("Diamond Jo Worth", 41),
    DRAGONARA("Dragonara Casino", 42),
    EASTSIDE_CANNERY("Eastside Cannery", 43),
    EXCALIBUR("Excalibur", 44),
    FIREKEEPERS_HOTEL("FireKeepers Casino Hotel", 45),
    FLAMINGO("Flamingo Las Vegas", 46),
    FORT_MCDOWELL("Fort McDowell", 47),
    FOXWOODS("Foxwoods Resort Casino", 48),
    FRASER_DOWNS("Fraser Downs", 49),
    FT_PIERCE_JAI_ALAI_POKER("Ft. Pierce Jai-Alai & Poker", 50),
    GOLDEN_GATES("The Golden Gates", 51),
    GOLDEN_NUGGET_ATLANTIC_CITY("Golden Nugget Atlantic City", 52),
    GOLDEN_WEST("Golden West Casino", 53),
    GRATON("Graton Resort & Casino", 54),
    GREEKTOWN_HOTEL("Greektown Casino-Hotel", 55),
    GREEN_VALLEY_RANCH("Green Valley Ranch", 56),
    GULFSTREAM_PARK("Gulfstream Park", 57),
    HARD_ROCK_LAS_VEGAS("Hard Rock Las Vegas", 58),
    HARD_ROCK_TULSA("Hard Rock Tulsa", 59),
    HARRAHS_AK_CHIN("Harrah's Ak-Chin", 60),
    HARRAHS_ATLANTIC_CITY("Harrah's Atlantic City", 61),
    HARRAHS_CHEROKEE("Harrah's Cherokee", 62),
    HARRAHS_JOLIET("Harrah's Joliet", 63),
    HARRAHS_LAS_VEGAS("Harrah's Las Vegas", 64),
    HARRAHS_LAUGHLIN("Harrah's Laughlin", 65),
    HARRAHS_NEW_ORLEANS("Harrah's New Orleans", 66),
    HARRAHS_NORTH_KANSAS_CITY("Harrah's North Kansas City", 67),
    HARRAHS_PHILADELPHIA("Harrah's Philadelphia", 68),
    HARRAHS_SOCAL("Harrah's Resort SoCal", 69),
    HARVEYS_LAKE_TAHOE("Harvey's Lake Tahoe", 70),
    HIALEAH_PARK("Hialeah Park Casino", 71),
    HOLLYWOOD_LAWRENCEBURG_IN("Hollywood Casino - Lawrenceburg, IN", 72),
    HOLLYWOOD_AT_PENN_NATIONAL("Hollywood Casino at Penn National", 73),
    HOLLYWOOD_AURORA("Hollywood Casino Aurora", 74),
    HOLLYWOOD_COLUMBUS("Hollywood Casino Columbus", 75),
    HOLLYWOOD_TOLEDO("Hollywood Casino Toledo", 76),
    HOLLYWOOD_CHARLES_TOWN("Hollywood Charles Town", 77),
    HOLLYWOOD_KANSAS_SPEEDWAY("Hollywood Kansas Speedway", 78),
    HOLLYWOOD_PERRYVILLE("Hollywood Perryville", 79),
    HOLLYWOOD_STL_POKER_STLOUISPOKERHC("Hollywood STL Poker @StLouisPokerHC", 80),
    HOLLYWOOD_TUNICA("Hollywood Tunica", 81),
    HORSESHOE_BALTIMORE("Horseshoe Baltimore", 82),
    HORSESHOE_BOSSIER_CITY("Horseshoe Bossier City", 83),
    HORSESHOE_CINCINNATI("Horseshoe Cincinnati", 84),
    HORSESHOE_CLEVELAND("Horseshoe Cleveland", 85),
    HORSESHOE_COUNCIL_BLUFFS("Horseshoe Council Bluffs", 86),
    HORSESHOE_HAMMOND("Horseshoe Hammond", 87),
    HORSESHOE_SOUTHERN_INDIANA("Horseshoe Southern Indiana", 88),
    HORSESHOE_TUNICA("Horseshoe Tunica", 89),
    INN_OF_THE_MOUNTAIN_GODS("Inn of the Mountain Gods", 90),
    IP("IP Casino Resort Spa", 91),
    ISLE_CASINO_CAPE("Isle Casino Cape", 92),
    ISLE_POMPANO_PARK("Isle Casino Pompano Park", 93),
    ISLE_WATERLOO("Isle Casino Waterloo", 94),
    ISLE_LAKE_CHARLES("Isle Lake Charles", 95),
    KANSAS_STAR("Kansas Star Casino", 96),
    LAKE_ELSINORE("Lake Elsinore Casino", 97),
    LAUBERGE_BATON_ROUGE("L'auberge Baton Rouge", 98),
    LAUBERGE("L'Auberge Casino Resort", 99),
    LODGE("The Lodge Casino", 100),
    LUMIERE_PLACE("Lumiere Place. The heart of poker in STL.", 101),
    LUXOR("Luxor", 102),
    MANDALAY_BAY("Mandalay Bay", 103),
    MARDI_GRAS_WEST_VIRGINIA("Mardi Gras West Virginia", 104),
    MARYLAND_LIVE("Maryland Live!", 105),
    MEADOWS_POKER_ROOM("The Meadows Poker Room", 106),
    MESKWAKI_BINGO("Meskwaki Bingo Casino Hotel", 107),
    MGM_GRAND("MGM Grand", 108),
    MIRAGE("The Mirage", 109),
    MOHEGAN_SUN("Mohegan Sun", 110),
    MOHEGAN_SUN_POCONO("Mohegan Sun Pocono", 111),
    MONTE_CARLO("Monte Carlo", 112),
    MONTEGO_BAY("Montego Bay", 113),
    MOUNT_AIRY("Mount Airy Casino", 114),
    MOUNTAINEER("Mountaineer", 115),
    MUCKLESHOOT("Muckleshoot Casino", 116),
    NORWEGIAN_CRUISE_LINES_POKER_CHALLENGE("Norwegian Cruise Lines Poker Challenge", 117),
    ONEIDA("Oneida Casino", 118),
    ORLEANS("The Orleans", 119),
    PALA("Pala Casino", 120),
    PALACE_LAKEWOOD("Palace Casino Lakewood", 121),
    PALACE_STATION("Palace Station", 122),
    PARX("Parx Casino", 123),
    PEARL_RIVER("Pearl River Resort", 124),
    PECHANGA("Pechanga", 125),
    PEPPERMILL("Peppermill Casino", 126),
    PLANET_HOLLYWOOD_LAS_VEGAS("Planet Hollywood Las Vegas", 127),
    PLAYGROUND_POKER_CLUB("Playground Poker Club", 128),
    PRESQUE_ISLE("Presque Isle", 129),
    QUECHAN("Quechan Casino", 130),
    RED_ROCK("Red Rock Casino", 131),
    RIO_LAS_VEGAS("Rio Las Vegas", 132),
    RIVER_CITY_POKER_ROOM("River City Poker Room", 133),
    RIVER_SPIRIT("River Spirit Casino", 134),
    RIVERS_PITTSBURGH("Rivers Casino Pittsburgh", 135),
    RIVERWIND("Riverwind Casino", 136),
    ROUTE_66("Route 66 Casino", 137),
    RUNNING_ACES("Running Aces", 138),
    SANDIA("Sandia Casino", 139),
    SANDS_BETHLEHEM("Sands Bethlehem", 140),
    SANTA_FE_STATION("Santa Fe Station", 141),
    SEMINOLE_BRIGHTON("Seminole Brighton", 142),
    SEMINOLE_COCONUT_CREEK("Seminole Coconut Creek", 143),
    SEMINOLE_HARD_ROCK_HOLLYWOOD("Seminole Hard Rock Hollywood", 144),
    SEMINOLE_HARD_ROCK_TAMPA("Seminole Hard Rock Tampa", 145),
    SEMINOLE_IMMOKALEE("Seminole Immokalee", 146),
    SILKS_POKER_ROOM("The Silks Poker Room", 147),
    SOARING_EAGLE("Soaring Eagle", 148),
    SOUTHPOINT("Southpoint", 149),
    SUGARHOUSE("SugarHouse Casino", 150),
    SYCUAN("Sycuan", 151),
    TABLE_MOUNTAIN("Table Mountain Casino", 152),
    TACHI_PALACE("Tachi Palace", 153),
    THUNDER_VALLEY("Thunder Valley Casino", 154),
    TOWERS("Towers Casino", 155),
    TREASURE_ISLAND("Treasure Island", 156),
    TULALIP("Tulalip Resort Casino", 157),
    TURNING_STONE("Turning Stone Resort Casino", 158),
    VEE_QUIVA("Vee Quiva Hotel & Casino", 159),
    VENETIAN("The Venetian", 160),
    WENDOVER_NUGGET("Wendover Nugget", 161),
    WHEELING_ISLAND("Wheeling Island Hotel Casino Racetrack", 162),
    WILD_HORSE_PASS("Wild Horse Pass", 163),
    WIN_RIVER("Win-River", 164),
    WINSTAR("WinStar World Casino", 165),
    WSOP_POKER_ROOM_BALLYS("WSOP Poker Room @ Bally's", 166),
    WYNN_LAS_VEGAS("Wynn Las Vegas", 167),
    GOLDEN_NUGGET("Golden Nugget Hotel & Casino", 169),
    BICYCLE("The Bicycle Casino", 170),
    NORMANDIE("Normandie Casino", 171),
    OCEANS_ELEVEN("Ocean's Eleven Casino", 172),
    HOLLYWOOD_PARK("Hollywood Park Casino", 173),
    HUSTLER("Hustler Casino", 174),
    BESTBET_ORANGE_PARK("bestbet Orange Park", 175),
    WILDHORSE("Wildhorse Resort Casino", 176),
    NAPLES_FORT_MYERS_GREYHOUND_AND_POKER("Naples Fort Myers Greyhound and Poker", 177),
    MAJESTIC_STAR("Majestic Star Casino", 178),
    BARRIERE_DE_LILLE("Hotel Casino Barriere de Lille", 179),
    SENECA_NIAGARA_AND_HOTEL("Seneca Niagara Casino and Hotel", 180),
    DOVER_DOWNS("Dover Downs", 181),
    LUCKY_CHANCES("Lucky Chances Casino", 182),
    CITY_OF_DREAMS_MACAU("City of Dreams, Macau", 183),
    GROSVENOR_LEEDS("Grosvenor Casino - Leeds", 184),
    ASPERS_WESTFIELD_STRATFORD_CITY("Aspers Casino Westfield Stratford City", 185),
    HO_CHUNK_GAMING_WISCONSIN_DELLS("Ho-Chunk Gaming Wisconsin Dells", 186),
    RAINBOW("Rainbow Casino", 187),
    KINGS("Kings Casino", 188),
    WATERFRONT("Waterfront Hotel and Casino", 189),
    TALKING_STICK("Talking Stick Resort", 190),
    BARCELONA("Casino Barcelona", 191),
    SOLAIRE("Solaire Resort & Casino", 192),
    CARD_PLAYER_CRUISES("Card Player Cruises", 193),
    BAY_101("Bay 101", 194),
    GRAND_SIERRA_AND("Grand Sierra Resort and Casino", 195),
    PERLA_HOTEL("Perla Casino & Hotel", 196),
    GROSVENOR_LUTON("Grosvenor Casino - Luton", 197),
    PALM_BEACH_KENNEL_CLUB("Palm Beach Kennel Club", 198),
    RESORTS_WORLD_MANILA("Resorts World Manila Casino", 199),
    HOLLAND("Holland Casino", 200),
    VILLA_MARINA_GAIETY_THEATRE("Villa Marina & Gaiety Theatre", 201),
    SPIELBANK_BERLIN("Spielbank Berlin", 202),
    CROWN("Crown Casino", 203),
    QUEENCO_HOTEL("Queenco Casino & Hotel", 204),
    AT_PORTOMASO("The Casino at Portomaso", 205),
    EMPERORS_PALACE("Emperors Palace", 206);
    
    private final String name;
    private final Integer id;

    private CasinoBank(String name, Integer id) {
	this.name = name;
	this.id = id;
    }

    public String getName() {
	return name;
    }

    public Integer getId() {
	return id;
    }    
}




















